// PSBT (BIP-174) inspection and re-serialization for EntropyLab, backed by
// rust-bitcoin 0.32.102 compiled to WebAssembly (Rust crate in psbt-wasm/,
// artifact generated by scripts/build-wasm.mjs into psbt-wasm-b64.js).
//
// Two functions cross the boundary, both over the same two-call convention
// (null output pointer reports the required capacity):
//
//   psbtInspectDoc(bytes) -> structured document describing the unsigned
//     transaction, every key-value pair of every map (typed decode for known
//     BIP-174/BIP-371 keys, raw hex for unknown ones), totals and fee, and
//     rust-bitcoin's own parse verdict.
//   psbtBuildBytes(doc)   -> PSBT bytes, after rust-bitcoin's
//     Psbt::deserialize has accepted the rebuilt file.
//
// Nothing here holds keys or generates randomness; the module only ever sees
// PSBT bytes and UTF-8 JSON. Loading mirrors secp256k1.js: browsers compile
// asynchronously (app boot waits on psbtWasmReady), Node initializes
// synchronously at import time so the test suite stays synchronous.
import { PSBT_WASM_B64 } from "./psbt-wasm-b64.js";

const wasmBytes = (() => {
  const binary = atob(PSBT_WASM_B64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
})();

let wasm = null; // WebAssembly exports; set by init below.

const isNode = typeof process !== "undefined" && !!(process.versions && process.versions.node);
if (isNode) {
  wasm = new WebAssembly.Instance(new WebAssembly.Module(wasmBytes), {}).exports;
}
export const psbtWasmReady = isNode
  ? Promise.resolve()
  : WebAssembly.instantiate(wasmBytes, {}).then(({ instance }) => {
      wasm = instance.exports;
    });

const requireReady = () => {
  if (!wasm) throw new Error("PSBT WebAssembly is not initialized yet; await psbtWasmReady.");
};
const heap = () => new Uint8Array(wasm.memory.buffer);
const encoder = new TextEncoder();
const decoder = new TextDecoder();

const lastError = () => {
  const needed = wasm.psbt_last_error(0, 0);
  if (needed <= 0) return "unknown PSBT WASM error";
  const ptr = wasm.psbt_alloc(needed);
  try {
    const length = wasm.psbt_last_error(ptr, needed);
    return length > 0 ? decoder.decode(heap().slice(ptr, ptr + length)) : "unknown PSBT WASM error";
  } finally {
    wasm.psbt_free(ptr, needed);
  }
};

const call = (input, fn) => {
  requireReady();
  const inPtr = wasm.psbt_alloc(input.length);
  heap().set(input, inPtr);
  try {
    const needed = fn(inPtr, input.length, 0, 0);
    if (needed < 0) throw new Error(lastError());
    const outPtr = wasm.psbt_alloc(needed);
    try {
      const length = fn(inPtr, input.length, outPtr, needed);
      if (length < 0) throw new Error(lastError());
      return heap().slice(outPtr, outPtr + length);
    } finally {
      wasm.psbt_free(outPtr, needed);
    }
  } finally {
    wasm.psbt_free(inPtr, input.length);
  }
};

export const psbtInspectDoc = (bytes) => {
  if (!(bytes instanceof Uint8Array) || !bytes.length) throw new Error("PSBT must be a non-empty byte array.");
  return JSON.parse(decoder.decode(call(bytes, wasm.psbt_inspect)));
};

export const psbtBuildBytes = (doc) => {
  if (!doc || typeof doc !== "object") throw new Error("editor document must be an object.");
  return call(encoder.encode(JSON.stringify(doc)), wasm.psbt_build);
};

// BIP-322 uses the same PSBT WASM instance. The Rust side exposes only a
// verifier: no signing primitive crosses this boundary.
export const bip322WasmVerify = (message, address, signature) => {
  requireReady();
  const messageBytes = encoder.encode(message);
  const addressBytes = encoder.encode(address);
  const signatureBytes = encoder.encode(signature);
  const messagePtr = wasm.psbt_alloc(messageBytes.length);
  const addressPtr = wasm.psbt_alloc(addressBytes.length);
  const signaturePtr = wasm.psbt_alloc(signatureBytes.length);
  try {
    heap().set(messageBytes, messagePtr);
    heap().set(addressBytes, addressPtr);
    heap().set(signatureBytes, signaturePtr);
    const needed = wasm.bip322_verify(messagePtr, messageBytes.length, addressPtr, addressBytes.length, signaturePtr, signatureBytes.length, 0, 0);
    if (needed < 0) throw new Error("BIP-322 WASM verifier failed");
    const outPtr = wasm.psbt_alloc(needed);
    try {
      const length = wasm.bip322_verify(messagePtr, messageBytes.length, addressPtr, addressBytes.length, signaturePtr, signatureBytes.length, outPtr, needed);
      if (length < 0) throw new Error("BIP-322 WASM verifier failed");
      return JSON.parse(decoder.decode(heap().slice(outPtr, outPtr + length)));
    } finally {
      wasm.psbt_free(outPtr, needed);
    }
  } finally {
    wasm.psbt_free(signaturePtr, signatureBytes.length);
    wasm.psbt_free(addressPtr, addressBytes.length);
    wasm.psbt_free(messagePtr, messageBytes.length);
  }
};
